== Guided Exercise: Deploying an Application to an OpenShift Cluster
In this exercise, you will use OpenShift to build and deploy an application
from a Dockerfile.

NOTE: Make sure you perform the clean up tasks at the end of each exercise.

=== Outcomes
You should be able to create an application using the *docker* build strategy,
and delete all resources from the application without deleting the project.

=== Before you begin
To perform this exercise, you need to ensure you have access to:

* A running OpenShift cluster
* The parent image for the sample application (*rhel7:7.3*)
* The sample application Git repository (*rhel7-echo*)

Run the following command on the *workstation* VM to validate the prerequisites
and to download solution files:
----
[student@workstation ~]$ lab docker-build setup
----

=== Steps
. Inspect the application Dockerfile project.
.. Clone the project from the classroom Git server to the *student* user's home
folder:
+
----
[student@workstation ~]$ git clone http://services.lab.example.com/rhel7-echo
----
.. Review the Dockerfile for the application:
+
----
[student@workstation ~]$ cat ~/rhel7-echo/Dockerfile
FROM registry.lab.example.com/rhel7:7.3  <1>
CMD bash -c "while true; do echo test; sleep 5; done"  <2>
----
+
<1> The parent image is the base OS image for Red Hat Enterprise Linux (RHEL)
7.3 from the Red Hat Container Catalog (RHCC).
<2> The application runs a loop that echoes "test" every five seconds.
. Build the application container image using the OpenShift cluster.
.. Log in to OpenShift as the *developer* user:
+
----
[student@workstation ~]$ oc login -u developer -p redhat \
     https://master.lab.example.com
----
.. Create a new project for the application:
+
----
[student@workstation ~] oc new-project docker-build
----
.. Create a new application from the Dockerfile project:
+
----
[student@workstation ~] oc new-app --name echo --insecure-registry \
    http://services.lab.example.com/rhel7-echo
...
--> Creating resources ...
    imagestream "rhel7" created
    imagestream "echo" created
    buildconfig "echo" created
    deploymentconfig "echo" created
--> Success
...
----
+
Ignore the warnings about failed registry lookups and image stream matches.
They are part of the algorithm to determine which resources to create.
+
The output shows that the *oc new-app* command correctly identified the URL
as a Git repository and created a build configuration.
.. Follow the build logs        
